env = "prod"
deployment_env = "prod"
vault_section = "prod"
packages_environment = "prod"
packages_version = "3.0.0"
business_services_persistence_baseUrl  = "http://probate-persistence-service-prod.service.core-compute-prod.internal"
business_services_notify_invitedata_inviteLink = "https://www.apply-for-probate.service.gov.uk/executors/invitation/"
pdf_service_url = "http://cmc-pdf-service-prod.service.core-compute-prod.internal"
s2s_service_api = "http://rpe-service-auth-provider-prod.service.core-compute-prod.internal"
evidence_management_host = "http://dm-store-prod.service.core-compute-prod.internal"

outbound_proxy = ""
log_level = "INFO"
capacity = "2"
asp_name = "probate-prod-asp-prod-asp"
asp_rg = "mgmt-asp-prod"